general {
    lock_cmd = pidof hyprlock || hyprlock       # Comando para bloquear
    before_sleep_cmd = loginctl lock-session    # Bloquear antes de suspender
}

# Bloquear a los 5 minutos (300 segundos)
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Apagar pantalla a los 10 minutos (600 segundos)
listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
