shell zsh

# Fuente
font_family      JetBrainsMono Nerd Font
font_size        13.0
window_padding_width 10

# Transparencia
background_opacity 0.85
dynamic_background_opacity yes
blur 1

# --- Colores CATPPUCCIN MOCHA ---
foreground            #CDD6F4
background            #1E1E2E
selection_foreground  #1E1E2E
selection_background  #F5E0DC

# Colores del cursor
cursor                #F5E0DC
cursor_text_color     #1E1E2E

# Colores ANSI
# Black
color0 #45475A
color8 #585B70
# Red
color1 #F38BA8
color9 #F38BA8
# Green
color2  #A6E3A1
color10 #A6E3A1
# Yellow
color3  #F9E2AF
color11 #F9E2AF
# Blue
color4  #89B4FA
color12 #89B4FA
# Magenta
color5  #F5C2E7
color13 #F5C2E7
# Cyan
color6  #94E2D5
color14 #94E2D5
# White
color7  #BAC2DE
color15 #A6ADC8

# Cursor
cursor #c0caf5
cursor_shape beam
